# Generated by Django 3.2.7 on 2021-09-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0004_auto_20210925_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
