# Generated by Django 3.2.7 on 2021-09-25 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0005_course_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrolledcourse',
            unique_together={('student', 'course')},
        ),
    ]
