# Generated by Django 3.2.7 on 2021-09-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0006_alter_enrolledcourse_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
